# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/cmake/phake/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/cmake/phake/cmake/IDE.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/cmake/phake/cmake/functions.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/cmake/phake/cmake/git.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/cmake/phake/cmake/libs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/cmake/phake/cmake/parse.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/cmake/phake/cmake/setup_configurations.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/dependencies/language/tests/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/philipwenkel/Github/flask/xbuild/_deps/catch-src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/CMakeParseArguments.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/CTest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/CTestTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/CTestUseLaunchers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/DartConfiguration.tcl.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/FetchContent.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/FetchContent/CMakeLists.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/FindBoost.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/FindGit.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.20.2/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/Boost-1.75.0/BoostConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/Boost-1.75.0/BoostConfigVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/boost_headers-1.75.0/boost_headers-config-version.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/boost_headers-1.75.0/boost_headers-config.cmake))

/Users/philipwenkel/Github/flask/xbuild/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.20.2/bin/cmake -H/Users/philipwenkel/Github/flask -B/Users/philipwenkel/Github/flask/xbuild
